#!/usr/bin/env sh

spacebar -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
spacebar -m config status_bar_icon_font         "Font Awesome 5 Free:Regular:12.0"
spacebar -m config status_bar_background_color  0xff202020
spacebar -m config status_bar_foreground_color  0xffa8a8a8
spacebar -m config status_bar_space_icon_strip  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
spacebar -m config status_bar_clock_format      "%Y-%m-%d %R"

echo "spacebar configuration loaded.."
